name: Deployer OASYS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-deployment-artifacts:
    name: Creer des artefacts de deploiement
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - name: Compiler les CSS et JS
    run: |
      npm install
      npm run build

  - name: Configurer PHP 8.2
    uses: shivammathur/setup-php@master
    with:
      php-version: 8.2
      extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

  - name: Composer install
    run: |
      composer install --no-dev --no-interaction --prefer-dist
